# Generated by Django 6.0.6 on 2026-06-06 07:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='unique_user_event',
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user_name', 'event')},
        ),
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registered_at',
        ),
    ]
